export default {
    "angleRight": "aicon-angle-right",
    "check": "aicon-check",
    "chevronUp": "aicon-chevron-up",
    "clock": "aicon-clock",
    "desktop": "aicon-desktop",
    "exit": "aicon-exit",
    "expIclub": "aicon-EXPIclub",
    "eye": "aicon-eye",
    "fileText": "aicon-file-text",
    "grid": "aicon-grid",
    "home": "aicon-home",
    "infoCircle": "aicon-info-circle",
    "internet": "aicon-internet",
    "layerGroup": "aicon-layer-group",
    "menu": "aicon-menu",
    "mobile": "aicon-mobile",
    "navigation": "aicon-navigation",
    "schloss": "aicon-Schloss",
    "ship": "aicon-ship",
    "smartphone": "aicon-smartphone",
    "snowflake": "aicon-snowflake",
    "tv": "aicon-tv",
    "zap": "aicon-zap"
};